In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_excel("./Siebanalyse_U1_5min_V1.xlsx",sheet_name="Einwaage",skiprows=4)
df

,Datum,Siebnr.:,do,du,Gewicht,Tara,Nachtara,Massenanteil [g],Massenanteil [%],Durchgang ∑ [%],g*M1,g*M2,g*M3,Massenanteil NT [g],spez Oberfl. [cm²/g]:,124.91159977175667
0,NaN,1,1.4,1,300.19,300.17,NaN,0.02,0.039984,99.96,0.376667,0.0236643,0.18,300.19,MK calc [mm]:,0.194532
1,NaN,2,1,0.71,272.77,272.74,NaN,0.03,0.059976,99.9,0.792982,0.0252784,0.45,272.77,AFS:,70.193723
2,NaN,3,0.71,0.5,258.04,258,NaN,0.04,0.079968,99.8201,1.49421,0.0238328,1,258.04,MK [mm]:,0.269000
3,NaN,4,0.5,0.355,234.84,234.46,NaN,0.38,0.759696,99.0604,20.0889,0.160097,13.3,234.84,GG [%]:,80.353175
4,NaN,5,0.355,0.25,229.97,224.56,NaN,5.41,10.8157,88.2447,404.185,1.61169,243.45,229.97,NaN,NaN
5,NaN,6,0.25,0.18,246.26,222.83,NaN,23.43,46.8413,41.4034,2462.87,4.97025,1405.8,246.26,NaN,NaN
6,NaN,7,0.18,0.125,229.51,212.93,NaN,16.58,33.1467,8.2567,2457.1,2.487,1342.98,229.51,NaN,NaN
7,NaN,8,0.125,0.09,207.48,203.59,NaN,3.89,7.77689,0.479808,817.805,0.412597,459.02,207.48,NaN,NaN
8,NaN,9,0.09,0.063,206.29,206.1,NaN,0.19,0.379848,0.09996,56.1307,0.0143069,31.16,206.29,NaN,NaN
9,NaN,10,0.063,0.02,216.64,216.59,NaN,0.05,0.09996,0,27.2289,0.00177482,13.75,216.64,NaN,NaN
10,NaN,11,0.02,0,321.62,321.62,NaN,0,0,NaN,NaN,NaN,NaN,0,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50.02,100,NaN,6248.08,9.73049,3511.09,2401.99,NaN,NaN
12,Probe 2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Datum,Siebnr.:,do,du,Gewicht,Tara,Nachtara,Massenanteil [g],Massenanteil [%],Durchgang ∑ [%],g*M1,g*M2,g*M3,Massenanteil NT [g],spez Oberfl. [cm²/g]:,126.200041
14,NaN,1,1.4,1,300.19,300.17,NaN,0.02,0.0399281,99.9601,0.376667,0.0236643,0.18,300.19,MK calc [mm]:,0.192071
15,NaN,2,1,0.71,272.76,272.76,NaN,0,0,99.9601,0,0,0,272.76,AFS:,70.864045
16,NaN,3,0.71,0.5,258.04,258,NaN,0.04,0.0798563,99.8802,1.49421,0.0238328,1,258.04,MK [mm]:,0.265000
17,NaN,4,0.5,0.355,234.74,234.43,NaN,0.31,0.618886,99.2613,16.3883,0.130605,10.85,234.74,GG [%]:,79.944446
18,NaN,5,0.355,0.25,229.68,224.52,NaN,5.16,10.3015,88.9599,385.507,1.53721,232.2,229.68,NaN,NaN
19,NaN,6,0.25,0.18,245.77,222.87,NaN,22.9,45.7177,43.2422,2407.16,4.85782,1374,245.77,NaN,NaN
20,NaN,7,0.18,0.125,230.2,212.92,NaN,17.28,34.4979,8.74426,2560.84,2.592,1399.68,230.2,NaN,NaN
21,NaN,8,0.125,0.09,207.72,203.59,NaN,4.13,8.24516,0.499102,868.26,0.438053,487.34,207.72,NaN,NaN
22,NaN,9,0.09,0.063,206.32,206.1,NaN,0.22,0.439209,0.0598922,64.9935,0.0165659,36.08,206.32,NaN,NaN
23,NaN,10,0.063,0.02,216.63,216.6,NaN,0.03,0.0598922,0,16.3373,0.00106489,8.25,216.63,NaN,NaN
24,NaN,11,0.02,0,321.62,321.62,NaN,0,0,NaN,NaN,NaN,NaN,321.62,NaN,NaN
25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50.09,100,NaN,6321.36,9.62082,3549.58,2723.67,NaN,NaN
26,Probe 3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,NaN,Siebnr.:,do,du,Gewicht,Tara,Nachtara,Massenanteil [g],Massenanteil [%],Durchgang ∑ [%],g*M1,g*M2,g*M3,Massenanteil NT [g],NaN,NaN
28,NaN,1,1.4,1,300.2,300.17,NaN,0.03,0.0598325,99.9402,0.565,0.0354965,0.27,300.2,spez Oberfl. [cm²/g]:,124.975111
29,NaN,2,1,0.71,272.78,272.76,NaN,0.02,0.0398883,99.9003,0.528655,0.0168523,0.3,272.78,MK calc [mm]:,0.194119
30,NaN,3,0.71,0.5,258.03,258,NaN,0.03,0.0598325,99.8404,1.12066,0.0178746,0.75,258.03,AFS:,70.235142
31,NaN,4,0.5,0.355,234.76,234.43,NaN,0.33,0.658157,99.1823,17.4456,0.139031,11.55,234.76,MK [mm]:,0.268000
32,NaN,5,0.355,0.25,230.02,224.52,NaN,5.5,10.9693,88.213,410.909,1.6385,247.5,230.02,GG [%]:,80.237967
33,NaN,6,0.25,0.18,246.12,222.87,NaN,23.25,46.3702,41.8428,2443.95,4.93207,1395,246.12,NaN,NaN
34,NaN,7,0.18,0.125,229.68,212.92,NaN,16.76,33.4264,8.41643,2483.78,2.514,1357.56,229.68,NaN,NaN
35,NaN,8,0.125,0.09,207.59,203.59,NaN,4,7.97766,0.438771,840.93,0.424264,472,207.59,NaN,NaN
36,NaN,9,0.09,0.063,206.29,206.1,NaN,0.19,0.378939,0.0598325,56.1307,0.0143069,31.16,206.29,NaN,NaN
37,NaN,10,0.063,0.02,216.62,216.6,NaN,0.02,0.0398883,0.0199442,10.8916,0.00070993,5.5,216.62,NaN,NaN
38,NaN,11,0.02,0,321.63,321.62,NaN,0.01,0.0199442,NaN,NaN,NaN,NaN,321.63,NaN,NaN
39,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50.14,100,NaN,6266.25,9.73311,3521.59,2723.72,NaN,NaN

In [3]:
df.drop(labels=['Datum','Nachtara'],axis=1,inplace=True)

In [4]:
df_1 = df[0:11]
df_1

,Siebnr.:,do,du,Gewicht,Tara,Massenanteil [g],Massenanteil [%],Durchgang ∑ [%],g*M1,g*M2,g*M3,Massenanteil NT [g],spez Oberfl. [cm²/g]:,124.91159977175667
0,1,1.4,1,300.19,300.17,0.02,0.039984,99.96,0.376667,0.0236643,0.18,300.19,MK calc [mm]:,0.194532
1,2,1,0.71,272.77,272.74,0.03,0.059976,99.9,0.792982,0.0252784,0.45,272.77,AFS:,70.193723
2,3,0.71,0.5,258.04,258,0.04,0.079968,99.8201,1.49421,0.0238328,1,258.04,MK [mm]:,0.269000
3,4,0.5,0.355,234.84,234.46,0.38,0.759696,99.0604,20.0889,0.160097,13.3,234.84,GG [%]:,80.353175
4,5,0.355,0.25,229.97,224.56,5.41,10.8157,88.2447,404.185,1.61169,243.45,229.97,NaN,NaN
5,6,0.25,0.18,246.26,222.83,23.43,46.8413,41.4034,2462.87,4.97025,1405.8,246.26,NaN,NaN
6,7,0.18,0.125,229.51,212.93,16.58,33.1467,8.2567,2457.1,2.487,1342.98,229.51,NaN,NaN
7,8,0.125,0.09,207.48,203.59,3.89,7.77689,0.479808,817.805,0.412597,459.02,207.48,NaN,NaN
8,9,0.09,0.063,206.29,206.1,0.19,0.379848,0.09996,56.1307,0.0143069,31.16,206.29,NaN,NaN
9,10,0.063,0.02,216.64,216.59,0.05,0.09996,0,27.2289,0.00177482,13.75,216.64,NaN,NaN
10,11,0.02,0,321.62,321.62,0,0,NaN,NaN,NaN,NaN,0,NaN,NaN

In [5]:
df_2 = df[14:25]
df_2

,Siebnr.:,do,du,Gewicht,Tara,Massenanteil [g],Massenanteil [%],Durchgang ∑ [%],g*M1,g*M2,g*M3,Massenanteil NT [g],spez Oberfl. [cm²/g]:,124.91159977175667
14,1,1.4,1,300.19,300.17,0.02,0.0399281,99.9601,0.376667,0.0236643,0.18,300.19,MK calc [mm]:,0.192071
15,2,1,0.71,272.76,272.76,0,0,99.9601,0,0,0,272.76,AFS:,70.864045
16,3,0.71,0.5,258.04,258,0.04,0.0798563,99.8802,1.49421,0.0238328,1,258.04,MK [mm]:,0.265000
17,4,0.5,0.355,234.74,234.43,0.31,0.618886,99.2613,16.3883,0.130605,10.85,234.74,GG [%]:,79.944446
18,5,0.355,0.25,229.68,224.52,5.16,10.3015,88.9599,385.507,1.53721,232.2,229.68,NaN,NaN
19,6,0.25,0.18,245.77,222.87,22.9,45.7177,43.2422,2407.16,4.85782,1374,245.77,NaN,NaN
20,7,0.18,0.125,230.2,212.92,17.28,34.4979,8.74426,2560.84,2.592,1399.68,230.2,NaN,NaN
21,8,0.125,0.09,207.72,203.59,4.13,8.24516,0.499102,868.26,0.438053,487.34,207.72,NaN,NaN
22,9,0.09,0.063,206.32,206.1,0.22,0.439209,0.0598922,64.9935,0.0165659,36.08,206.32,NaN,NaN
23,10,0.063,0.02,216.63,216.6,0.03,0.0598922,0,16.3373,0.00106489,8.25,216.63,NaN,NaN
24,11,0.02,0,321.62,321.62,0,0,NaN,NaN,NaN,NaN,321.62,NaN,NaN

In [6]:
df_3 = df[28:39]
df_3

,Siebnr.:,do,du,Gewicht,Tara,Massenanteil [g],Massenanteil [%],Durchgang ∑ [%],g*M1,g*M2,g*M3,Massenanteil NT [g],spez Oberfl. [cm²/g]:,124.91159977175667
28,1,1.4,1,300.2,300.17,0.03,0.0598325,99.9402,0.565,0.0354965,0.27,300.2,spez Oberfl. [cm²/g]:,124.975111
29,2,1,0.71,272.78,272.76,0.02,0.0398883,99.9003,0.528655,0.0168523,0.3,272.78,MK calc [mm]:,0.194119
30,3,0.71,0.5,258.03,258,0.03,0.0598325,99.8404,1.12066,0.0178746,0.75,258.03,AFS:,70.235142
31,4,0.5,0.355,234.76,234.43,0.33,0.658157,99.1823,17.4456,0.139031,11.55,234.76,MK [mm]:,0.268000
32,5,0.355,0.25,230.02,224.52,5.5,10.9693,88.213,410.909,1.6385,247.5,230.02,GG [%]:,80.237967
33,6,0.25,0.18,246.12,222.87,23.25,46.3702,41.8428,2443.95,4.93207,1395,246.12,NaN,NaN
34,7,0.18,0.125,229.68,212.92,16.76,33.4264,8.41643,2483.78,2.514,1357.56,229.68,NaN,NaN
35,8,0.125,0.09,207.59,203.59,4,7.97766,0.438771,840.93,0.424264,472,207.59,NaN,NaN
36,9,0.09,0.063,206.29,206.1,0.19,0.378939,0.0598325,56.1307,0.0143069,31.16,206.29,NaN,NaN
37,10,0.063,0.02,216.62,216.6,0.02,0.0398883,0.0199442,10.8916,0.00070993,5.5,216.62,NaN,NaN
38,11,0.02,0,321.63,321.62,0.01,0.0199442,NaN,NaN,NaN,NaN,321.63,NaN,NaN

In [7]:
total_columns = len(df_1.columns)
total_columns

14

In [8]:
df_1 = df_1.iloc[:,0:total_columns-2]
df_2 = df_2.iloc[:,0:total_columns-2]
df_3 = df_3.iloc[:,0:total_columns-2]
df_1

,Siebnr.:,do,du,Gewicht,Tara,Massenanteil [g],Massenanteil [%],Durchgang ∑ [%],g*M1,g*M2,g*M3,Massenanteil NT [g]
0,1,1.4,1,300.19,300.17,0.02,0.039984,99.96,0.376667,0.0236643,0.18,300.19
1,2,1,0.71,272.77,272.74,0.03,0.059976,99.9,0.792982,0.0252784,0.45,272.77
2,3,0.71,0.5,258.04,258,0.04,0.079968,99.8201,1.49421,0.0238328,1,258.04
3,4,0.5,0.355,234.84,234.46,0.38,0.759696,99.0604,20.0889,0.160097,13.3,234.84
4,5,0.355,0.25,229.97,224.56,5.41,10.8157,88.2447,404.185,1.61169,243.45,229.97
5,6,0.25,0.18,246.26,222.83,23.43,46.8413,41.4034,2462.87,4.97025,1405.8,246.26
6,7,0.18,0.125,229.51,212.93,16.58,33.1467,8.2567,2457.1,2.487,1342.98,229.51
7,8,0.125,0.09,207.48,203.59,3.89,7.77689,0.479808,817.805,0.412597,459.02,207.48
8,9,0.09,0.063,206.29,206.1,0.19,0.379848,0.09996,56.1307,0.0143069,31.16,206.29
9,10,0.063,0.02,216.64,216.59,0.05,0.09996,0,27.2289,0.00177482,13.75,216.64
10,11,0.02,0,321.62,321.62,0,0,NaN,NaN,NaN,NaN,0

In [9]:
df_2

,Siebnr.:,do,du,Gewicht,Tara,Massenanteil [g],Massenanteil [%],Durchgang ∑ [%],g*M1,g*M2,g*M3,Massenanteil NT [g]
14,1,1.4,1,300.19,300.17,0.02,0.0399281,99.9601,0.376667,0.0236643,0.18,300.19
15,2,1,0.71,272.76,272.76,0,0,99.9601,0,0,0,272.76
16,3,0.71,0.5,258.04,258,0.04,0.0798563,99.8802,1.49421,0.0238328,1,258.04
17,4,0.5,0.355,234.74,234.43,0.31,0.618886,99.2613,16.3883,0.130605,10.85,234.74
18,5,0.355,0.25,229.68,224.52,5.16,10.3015,88.9599,385.507,1.53721,232.2,229.68
19,6,0.25,0.18,245.77,222.87,22.9,45.7177,43.2422,2407.16,4.85782,1374,245.77
20,7,0.18,0.125,230.2,212.92,17.28,34.4979,8.74426,2560.84,2.592,1399.68,230.2
21,8,0.125,0.09,207.72,203.59,4.13,8.24516,0.499102,868.26,0.438053,487.34,207.72
22,9,0.09,0.063,206.32,206.1,0.22,0.439209,0.0598922,64.9935,0.0165659,36.08,206.32
23,10,0.063,0.02,216.63,216.6,0.03,0.0598922,0,16.3373,0.00106489,8.25,216.63
24,11,0.02,0,321.62,321.62,0,0,NaN,NaN,NaN,NaN,321.62

In [10]:
df_3

,Siebnr.:,do,du,Gewicht,Tara,Massenanteil [g],Massenanteil [%],Durchgang ∑ [%],g*M1,g*M2,g*M3,Massenanteil NT [g]
28,1,1.4,1,300.2,300.17,0.03,0.0598325,99.9402,0.565,0.0354965,0.27,300.2
29,2,1,0.71,272.78,272.76,0.02,0.0398883,99.9003,0.528655,0.0168523,0.3,272.78
30,3,0.71,0.5,258.03,258,0.03,0.0598325,99.8404,1.12066,0.0178746,0.75,258.03
31,4,0.5,0.355,234.76,234.43,0.33,0.658157,99.1823,17.4456,0.139031,11.55,234.76
32,5,0.355,0.25,230.02,224.52,5.5,10.9693,88.213,410.909,1.6385,247.5,230.02
33,6,0.25,0.18,246.12,222.87,23.25,46.3702,41.8428,2443.95,4.93207,1395,246.12
34,7,0.18,0.125,229.68,212.92,16.76,33.4264,8.41643,2483.78,2.514,1357.56,229.68
35,8,0.125,0.09,207.59,203.59,4,7.97766,0.438771,840.93,0.424264,472,207.59
36,9,0.09,0.063,206.29,206.1,0.19,0.378939,0.0598325,56.1307,0.0143069,31.16,206.29
37,10,0.063,0.02,216.62,216.6,0.02,0.0398883,0.0199442,10.8916,0.00070993,5.5,216.62
38,11,0.02,0,321.63,321.62,0.01,0.0199442,NaN,NaN,NaN,NaN,321.63

In [11]:
# configurations
# For probe-1 => spez Oberfl. [cm²/g] = 124.91 , MK calc [mm] = 0.19 , AFS = 70 , MK [mm] = 0.2696 , GG[%] = 80.35
# For probe-1 => spez Oberfl. [cm²/g] = 126.20 , MK calc [mm] = 0.19 , AFS = 71 , MK [mm] = 0.27 , GG[%] = 79.94
# For probe-1 => spez Oberfl. [cm²/g] = 124.98 , MK calc [mm] = 0.19 , AFS = 70 , MK [mm] = 0.27 , GG[%] = 80.24

In [12]:
def get_configs(a,b,c,d,e):
    spez = []
    Mk_calc = []
    AFS = []
    MK = []
    GG = []
    for x in range(len(df_1)):
        spez.append(a)
        Mk_calc.append(b)
        AFS.append(c)
        MK.append(d)
        GG.append(e)

    return spez,Mk_calc,AFS,MK,GG

In [13]:
spez,Mk_calc,AFS,MK,GG   = get_configs(124.91,0.19,70,0.2696,80.35) # for probe-1
df_1['spez Oberfl. [cm²/g]'] = spez
df_1['MK calc [mm]'] = Mk_calc
df_1['AFS'] = AFS
df_1['MK [mm]'] = MK
df_1['GG [%]'] = GG

spez,Mk_calc,AFS,MK,GG   = get_configs(126.20,0.19,71,0.27,80.24) # for probe-2
df_2['spez Oberfl. [cm²/g]'] = spez
df_2['MK calc [mm]'] = Mk_calc
df_2['AFS'] = AFS
df_2['MK [mm]'] = MK
df_2['GG [%]'] = GG

spez,Mk_calc,AFS,MK,GG   = get_configs(124.98,0.19,70,0.27,80.35) # for probe-3
df_3['spez Oberfl. [cm²/g]'] = spez
df_3['MK calc [mm]'] = Mk_calc
df_3['AFS'] = AFS
df_3['MK [mm]'] = MK
df_3['GG [%]'] = GG

In [14]:
df_1.fillna(value=0,inplace=True)
df_2.fillna(value=0,inplace=True)
df_3.fillna(value=0,inplace=True)

In [15]:
# getting final dataframe
final_df = pd.concat([df_1,df_2,df_3],ignore_index=True)
final_df

,Siebnr.:,do,du,Gewicht,Tara,Massenanteil [g],Massenanteil [%],Durchgang ∑ [%],g*M1,g*M2,g*M3,Massenanteil NT [g],spez Oberfl. [cm²/g],MK calc [mm],AFS,MK [mm],GG [%]
0,1,1.400,1.000,300.19,300.17,0.02,0.039984,99.960016,0.376667,0.023664,0.18,300.19,124.91,0.19,70,0.2696,80.35
1,2,1.000,0.710,272.77,272.74,0.03,0.059976,99.900040,0.792982,0.025278,0.45,272.77,124.91,0.19,70,0.2696,80.35
2,3,0.710,0.500,258.04,258.00,0.04,0.079968,99.820072,1.494215,0.023833,1.00,258.04,124.91,0.19,70,0.2696,80.35
3,4,0.500,0.355,234.84,234.46,0.38,0.759696,99.060376,20.088889,0.160097,13.30,234.84,124.91,0.19,70,0.2696,80.35
4,5,0.355,0.250,229.97,224.56,5.41,10.815674,88.244702,404.185124,1.611690,243.45,229.97,124.91,0.19,70,0.2696,80.35
5,6,0.250,0.180,246.26,222.83,23.43,46.841263,41.403439,2462.874419,4.970254,1405.80,246.26,124.91,0.19,70,0.2696,80.35
6,7,0.180,0.125,229.51,212.93,16.58,33.146741,8.256697,2457.101639,2.487000,1342.98,229.51,124.91,0.19,70,0.2696,80.35
7,8,0.125,0.090,207.48,203.59,3.89,7.776889,0.479808,817.804651,0.412597,459.02,207.48,124.91,0.19,70,0.2696,80.35
8,9,0.090,0.063,206.29,206.10,0.19,0.379848,0.099960,56.130719,0.014307,31.16,206.29,124.91,0.19,70,0.2696,80.35
9,10,0.063,0.020,216.64,216.59,0.05,0.099960,0.000000,27.228916,0.001775,13.75,216.64,124.91,0.19,70,0.2696,80.35
10,11,0.020,0.000,321.62,321.62,0.00,0.000000,0.000000,0.000000,0.000000,0.00,0.00,124.91,0.19,70,0.2696,80.35
11,1,1.400,1.000,300.19,300.17,0.02,0.039928,99.960072,0.376667,0.023664,0.18,300.19,126.20,0.19,71,0.2700,80.24
12,2,1.000,0.710,272.76,272.76,0.00,0.000000,99.960072,0.000000,0.000000,0.00,272.76,126.20,0.19,71,0.2700,80.24
13,3,0.710,0.500,258.04,258.00,0.04,0.079856,99.880216,1.494215,0.023833,1.00,258.04,126.20,0.19,71,0.2700,80.24
14,4,0.500,0.355,234.74,234.43,0.31,0.618886,99.261330,16.388304,0.130605,10.85,234.74,126.20,0.19,71,0.2700,80.24
15,5,0.355,0.250,229.68,224.52,5.16,10.301457,88.959872,385.507438,1.537212,232.20,229.68,126.20,0.19,71,0.2700,80.24
16,6,0.250,0.180,245.77,222.87,22.90,45.717708,43.242164,2407.162791,4.857824,1374.00,245.77,126.20,0.19,71,0.2700,80.24
17,7,0.180,0.125,230.20,212.92,17.28,34.497904,8.744260,2560.839344,2.592000,1399.68,230.20,126.20,0.19,71,0.2700,80.24
18,8,0.125,0.090,207.72,203.59,4.13,8.245159,0.499102,868.260465,0.438053,487.34,207.72,126.20,0.19,71,0.2700,80.24
19,9,0.090,0.063,206.32,206.10,0.22,0.439209,0.059892,64.993464,0.016566,36.08,206.32,126.20,0.19,71,0.2700,80.24
20,10,0.063,0.020,216.63,216.60,0.03,0.059892,0.000000,16.337349,0.001065,8.25,216.63,126.20,0.19,71,0.2700,80.24
21,11,0.020,0.000,321.62,321.62,0.00,0.000000,0.000000,0.000000,0.000000,0.00,321.62,126.20,0.19,71,0.2700,80.24
22,1,1.400,1.000,300.20,300.17,0.03,0.059832,99.940168,0.565000,0.035496,0.27,300.20,124.98,0.19,70,0.2700,80.35
23,2,1.000,0.710,272.78,272.76,0.02,0.039888,99.900279,0.528655,0.016852,0.30,272.78,124.98,0.19,70,0.2700,80.35
24,3,0.710,0.500,258.03,258.00,0.03,0.059832,99.840447,1.120661,0.017875,0.75,258.03,124.98,0.19,70,0.2700,80.35
25,4,0.500,0.355,234.76,234.43,0.33,0.658157,99.182290,17.445614,0.139031,11.55,234.76,124.98,0.19,70,0.2700,80.35
26,5,0.355,0.250,230.02,224.52,5.50,10.969286,88.213004,410.909091,1.638502,247.50,230.02,124.98,0.19,70,0.2700,80.35
27,6,0.250,0.180,246.12,222.87,23.25,46.370164,41.842840,2443.953488,4.932070,1395.00,246.12,124.98,0.19,70,0.2700,80.35
28,7,0.180,0.125,229.68,212.92,16.76,33.426406,8.416434,2483.777049,2.514000,1357.56,229.68,124.98,0.19,70,0.2700,80.35
29,8,0.125,0.090,207.59,203.59,4.00,7.977663,0.438771,840.930233,0.424264,472.00,207.59,124.98,0.19,70,0.2700,80.35
30,9,0.090,0.063,206.29,206.10,0.19,0.378939,0.059832,56.130719,0.014307,31.16,206.29,124.98,0.19,70,0.2700,80.35
31,10,0.063,0.020,216.62,216.60,0.02,0.039888,0.019944,10.891566,0.000710,5.50,216.62,124.98,0.19,70,0.2700,80.35
32,11,0.020,0.000,321.63,321.62,0.01,0.019944,0.000000,0.000000,0.000000,0.00,321.63,124.98,0.19,70,0.2700,80.35

In [16]:
# check correlation
correlation_data = final_df.corr()
cols_to_be_selected = []
all_cols = correlation_data.columns
index = 0;

for x in correlation_data['Massenanteil [%]'].tolist():
    if(x >= -0.25 and x <=0.25):
        #neglecting the feature / column
        pass
    else:
        cols_to_be_selected.append(all_cols[index])
    index += 1

cols_to_be_selected

['do',
 'du',
 'Tara',
 'Massenanteil [g]',
 'Massenanteil [%]',
 'g*M1',
 'g*M2',
 'g*M3']

In [17]:
features = final_df[['do',
 'du',
 'Tara',
 'Massenanteil [g]',
 'g*M1',
 'g*M2',
 'g*M3']]

target = final_df[['Massenanteil [%]']]

In [19]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_validate
reg = LinearRegression()
model = cross_validate(reg,features,target,cv=10,scoring='r2',return_estimator=True)
model

{'estimator': [LinearRegression(),
  LinearRegression(),
  LinearRegression(),
  LinearRegression(),
  LinearRegression(),
  LinearRegression(),
  LinearRegression(),
  LinearRegression(),
  LinearRegression(),
  LinearRegression()],
 'fit_time': array([0.00897384, 0.00598288, 0.01196671, 0.00698137, 0.00697947,
        0.004987  , 0.0069797 , 0.0049839 , 0.00398898, 0.00797892]),
 'score_time': array([0.00599027, 0.00598407, 0.00402021, 0.00399065, 0.00399089,
        0.00398898, 0.00698423, 0.00598383, 0.00498796, 0.004987  ]),
 'test_score': array([0.99999703, 0.99998801, 0.99999726, 0.99999984, 0.99999979,
        0.99999996, 0.99999463, 0.99999521, 0.99998741, 0.99999315])}

In [31]:
final_model = model['estimator'][0]
final_model.coef_[0][6]

1.4993485376130385e-05

In [22]:
final_model.intercept_

array([0.00023827])

In [34]:
# So the final equation is :
# [ (do * 0.00203) +  (du * -0.002) + (Tara * - 0.000000009 ) + (Massenanteil [g] * 1.9972) + (g*M1 * -0.0000107 ) + (g*M2 * -0.0017 ) + (g*M3 * 0.000015 ) ] + 0.00023827
'''[ (do * 0.00203) +  (du * -0.002) + (Tara * - 0.000000009 ) + (Massenanteil [g] * 1.9972) + (g*M1 * -0.0000107 ) + (g*M2 * -0.0017 ) + (g*M3 * 0.000015 ) ] + 0.00023827'''

'[ (do * 0.00203) +  (du * -0.002) + (Tara * - 0.000000009 ) + (Massenanteil [g] * 1.9972) + (g*M1 * -0.0000107 ) + (g*M2 * -0.0017 ) + (g*M3 * 0.000015 ) ] + 0.00023827'

In [35]:
# This equation will help us to predict Massenanteil [%]