In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_excel("./Siebanalyse_U1_10min_V1 (1).xlsx",sheet_name="Einwaage",skiprows=4)
df

,Datum,Siebnr.:,do,du,Gewicht,Tara,Nachtara,Massenanteil [g],Massenanteil [%],Durchgang ∑ [%],g*M1,g*M2,g*M3,Massenanteil NT [g],spez Oberfl. [cm²/g]:,125.28906756086838
0,NaN,1,1.4,1,300.17,300.16,NaN,0.01,0.019685,99.9803,0.188333,0.0118322,0.09,300.17,MK calc [mm]:,0.193170
1,NaN,2,1,0.71,272.75,272.73,NaN,0.02,0.0393701,99.9409,0.528655,0.0168523,0.3,272.75,AFS:,70.382087
2,NaN,3,0.71,0.5,258.03,258,NaN,0.03,0.0590551,99.8819,1.12066,0.0178746,0.75,258.03,MK [mm]:,0.268000
3,NaN,4,0.5,0.355,234.68,234.39,NaN,0.29,0.570866,99.311,15.331,0.122179,10.15,234.68,GG [%]:,81.188273
4,NaN,5,0.355,0.25,229.76,224.5,NaN,5.26,10.3543,88.9567,392.979,1.567,236.7,229.76,NaN,NaN
5,NaN,6,0.25,0.18,246.93,222.92,NaN,24.01,47.2638,41.6929,2523.84,5.09329,1440.6,246.93,NaN,NaN
6,NaN,7,0.18,0.125,229.97,212.95,NaN,17.02,33.5039,8.18898,2522.31,2.553,1378.62,229.97,NaN,NaN
7,NaN,8,0.125,0.09,207.48,203.6,NaN,3.88,7.6378,0.551181,815.702,0.411536,457.84,207.48,NaN,NaN
8,NaN,9,0.09,0.063,206.32,206.08,NaN,0.24,0.472441,0.0787402,70.902,0.0180719,39.36,206.32,NaN,NaN
9,NaN,10,0.063,0.02,216.62,216.58,NaN,0.04,0.0787402,0,21.7831,0.00141986,11,216.62,NaN,NaN
10,NaN,11,0.02,0,321.62,321.62,NaN,0,0,NaN,NaN,NaN,NaN,0,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50.8,100,NaN,6364.68,9.81306,3575.41,2402.71,NaN,NaN
12,Probe 2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Datum,Siebnr.:,do,du,Gewicht,Tara,Nachtara,Massenanteil [g],Massenanteil [%],Durchgang ∑ [%],g*M1,g*M2,g*M3,Massenanteil NT [g],spez Oberfl. [cm²/g]:,124.946231
14,NaN,1,1.4,1,300.16,300.15,NaN,0.01,0.0198886,99.9801,0.188333,0.0118322,0.09,300.16,MK calc [mm]:,0.193441
15,NaN,2,1,0.71,272.75,272.74,NaN,0.01,0.0198886,99.9602,0.264327,0.00842615,0.15,272.75,AFS:,70.207239
16,NaN,3,0.71,0.5,258.01,257.98,NaN,0.03,0.0596659,99.9006,1.12066,0.0178746,0.75,258.01,MK [mm]:,0.269000
17,NaN,4,0.5,0.355,234.67,234.37,NaN,0.3,0.596659,99.3039,15.8596,0.126392,10.5,234.67,GG [%]:,81.180711
18,NaN,5,0.355,0.25,229.74,224.51,NaN,5.23,10.4018,88.9021,390.737,1.55807,235.35,229.74,NaN,NaN
19,NaN,6,0.25,0.18,246.92,223.01,NaN,23.91,47.5537,41.3484,2513.33,5.07208,1434.6,246.92,NaN,NaN
20,NaN,7,0.18,0.125,229.68,212.95,NaN,16.73,33.2737,8.07478,2479.33,2.5095,1355.13,229.68,NaN,NaN
21,NaN,8,0.125,0.09,207.43,203.61,NaN,3.82,7.59745,0.477327,803.088,0.405172,450.76,207.43,NaN,NaN
22,NaN,9,0.09,0.063,206.33,206.12,NaN,0.21,0.417661,0.0596659,62.0392,0.0158129,34.44,206.33,NaN,NaN
23,NaN,10,0.063,0.02,216.63,216.6,NaN,0.03,0.0596659,0,16.3373,0.00106489,8.25,216.63,NaN,NaN
24,NaN,11,0.02,0,321.62,321.62,NaN,0,0,NaN,NaN,NaN,NaN,321.62,NaN,NaN
25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50.28,100,NaN,6282.3,9.72622,3530.02,2723.94,NaN,NaN
26,Probe 3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,NaN,Siebnr.:,do,du,Gewicht,Tara,Nachtara,Massenanteil [g],Massenanteil [%],Durchgang ∑ [%],g*M1,g*M2,g*M3,Massenanteil NT [g],NaN,NaN
28,NaN,1,1.4,1,300.17,300.15,NaN,0.02,0.0397062,99.9603,0.376667,0.0236643,0.18,300.17,spez Oberfl. [cm²/g]:,124.876041
29,NaN,2,1,0.71,272.76,272.74,NaN,0.02,0.0397062,99.9206,0.528655,0.0168523,0.3,272.76,MK calc [mm]:,0.193711
30,NaN,3,0.71,0.5,258.01,257.98,NaN,0.03,0.0595593,99.861,1.12066,0.0178746,0.75,258.01,AFS:,70.174707
31,NaN,4,0.5,0.355,234.67,234.37,NaN,0.3,0.595593,99.2654,15.8596,0.126392,10.5,234.67,MK [mm]:,0.269000
32,NaN,5,0.355,0.25,229.64,224.51,NaN,5.13,10.1846,89.0808,383.266,1.52828,230.85,229.64,GG [%]:,81.253184
33,NaN,6,0.25,0.18,247.19,223.01,NaN,24.18,48.0048,41.076,2541.71,5.12935,1450.8,247.19,NaN,NaN
34,NaN,7,0.18,0.125,229.52,212.95,NaN,16.57,32.8966,8.17947,2455.62,2.4855,1342.17,229.52,NaN,NaN
35,NaN,8,0.125,0.09,207.52,203.61,NaN,3.91,7.76256,0.416915,822.009,0.414718,461.38,207.52,NaN,NaN
36,NaN,9,0.09,0.063,206.3,206.12,NaN,0.18,0.357356,0.0595593,53.1765,0.0135539,29.52,206.3,NaN,NaN
37,NaN,10,0.063,0.02,216.63,216.6,NaN,0.03,0.0595593,0,16.3373,0.00106489,8.25,216.63,NaN,NaN
38,NaN,11,0.02,0,321.62,321.62,NaN,0,0,NaN,NaN,NaN,NaN,321.62,NaN,NaN
39,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50.37,100,NaN,6290.01,9.75725,3534.7,2724.03,NaN,NaN

In [3]:
df.drop(labels=['Datum','Nachtara'],axis=1,inplace=True)

In [4]:
df_1 = df[0:11]
df_1

,Siebnr.:,do,du,Gewicht,Tara,Massenanteil [g],Massenanteil [%],Durchgang ∑ [%],g*M1,g*M2,g*M3,Massenanteil NT [g],spez Oberfl. [cm²/g]:,125.28906756086838
0,1,1.4,1,300.17,300.16,0.01,0.019685,99.9803,0.188333,0.0118322,0.09,300.17,MK calc [mm]:,0.193170
1,2,1,0.71,272.75,272.73,0.02,0.0393701,99.9409,0.528655,0.0168523,0.3,272.75,AFS:,70.382087
2,3,0.71,0.5,258.03,258,0.03,0.0590551,99.8819,1.12066,0.0178746,0.75,258.03,MK [mm]:,0.268000
3,4,0.5,0.355,234.68,234.39,0.29,0.570866,99.311,15.331,0.122179,10.15,234.68,GG [%]:,81.188273
4,5,0.355,0.25,229.76,224.5,5.26,10.3543,88.9567,392.979,1.567,236.7,229.76,NaN,NaN
5,6,0.25,0.18,246.93,222.92,24.01,47.2638,41.6929,2523.84,5.09329,1440.6,246.93,NaN,NaN
6,7,0.18,0.125,229.97,212.95,17.02,33.5039,8.18898,2522.31,2.553,1378.62,229.97,NaN,NaN
7,8,0.125,0.09,207.48,203.6,3.88,7.6378,0.551181,815.702,0.411536,457.84,207.48,NaN,NaN
8,9,0.09,0.063,206.32,206.08,0.24,0.472441,0.0787402,70.902,0.0180719,39.36,206.32,NaN,NaN
9,10,0.063,0.02,216.62,216.58,0.04,0.0787402,0,21.7831,0.00141986,11,216.62,NaN,NaN
10,11,0.02,0,321.62,321.62,0,0,NaN,NaN,NaN,NaN,0,NaN,NaN

In [5]:
df_2 = df[14:25]
df_2

,Siebnr.:,do,du,Gewicht,Tara,Massenanteil [g],Massenanteil [%],Durchgang ∑ [%],g*M1,g*M2,g*M3,Massenanteil NT [g],spez Oberfl. [cm²/g]:,125.28906756086838
14,1,1.4,1,300.16,300.15,0.01,0.0198886,99.9801,0.188333,0.0118322,0.09,300.16,MK calc [mm]:,0.193441
15,2,1,0.71,272.75,272.74,0.01,0.0198886,99.9602,0.264327,0.00842615,0.15,272.75,AFS:,70.207239
16,3,0.71,0.5,258.01,257.98,0.03,0.0596659,99.9006,1.12066,0.0178746,0.75,258.01,MK [mm]:,0.269000
17,4,0.5,0.355,234.67,234.37,0.3,0.596659,99.3039,15.8596,0.126392,10.5,234.67,GG [%]:,81.180711
18,5,0.355,0.25,229.74,224.51,5.23,10.4018,88.9021,390.737,1.55807,235.35,229.74,NaN,NaN
19,6,0.25,0.18,246.92,223.01,23.91,47.5537,41.3484,2513.33,5.07208,1434.6,246.92,NaN,NaN
20,7,0.18,0.125,229.68,212.95,16.73,33.2737,8.07478,2479.33,2.5095,1355.13,229.68,NaN,NaN
21,8,0.125,0.09,207.43,203.61,3.82,7.59745,0.477327,803.088,0.405172,450.76,207.43,NaN,NaN
22,9,0.09,0.063,206.33,206.12,0.21,0.417661,0.0596659,62.0392,0.0158129,34.44,206.33,NaN,NaN
23,10,0.063,0.02,216.63,216.6,0.03,0.0596659,0,16.3373,0.00106489,8.25,216.63,NaN,NaN
24,11,0.02,0,321.62,321.62,0,0,NaN,NaN,NaN,NaN,321.62,NaN,NaN

In [6]:
df_3 = df[28:39]
df_3

,Siebnr.:,do,du,Gewicht,Tara,Massenanteil [g],Massenanteil [%],Durchgang ∑ [%],g*M1,g*M2,g*M3,Massenanteil NT [g],spez Oberfl. [cm²/g]:,125.28906756086838
28,1,1.4,1,300.17,300.15,0.02,0.0397062,99.9603,0.376667,0.0236643,0.18,300.17,spez Oberfl. [cm²/g]:,124.876041
29,2,1,0.71,272.76,272.74,0.02,0.0397062,99.9206,0.528655,0.0168523,0.3,272.76,MK calc [mm]:,0.193711
30,3,0.71,0.5,258.01,257.98,0.03,0.0595593,99.861,1.12066,0.0178746,0.75,258.01,AFS:,70.174707
31,4,0.5,0.355,234.67,234.37,0.3,0.595593,99.2654,15.8596,0.126392,10.5,234.67,MK [mm]:,0.269000
32,5,0.355,0.25,229.64,224.51,5.13,10.1846,89.0808,383.266,1.52828,230.85,229.64,GG [%]:,81.253184
33,6,0.25,0.18,247.19,223.01,24.18,48.0048,41.076,2541.71,5.12935,1450.8,247.19,NaN,NaN
34,7,0.18,0.125,229.52,212.95,16.57,32.8966,8.17947,2455.62,2.4855,1342.17,229.52,NaN,NaN
35,8,0.125,0.09,207.52,203.61,3.91,7.76256,0.416915,822.009,0.414718,461.38,207.52,NaN,NaN
36,9,0.09,0.063,206.3,206.12,0.18,0.357356,0.0595593,53.1765,0.0135539,29.52,206.3,NaN,NaN
37,10,0.063,0.02,216.63,216.6,0.03,0.0595593,0,16.3373,0.00106489,8.25,216.63,NaN,NaN
38,11,0.02,0,321.62,321.62,0,0,NaN,NaN,NaN,NaN,321.62,NaN,NaN

In [7]:
total_columns = len(df_1.columns)
total_columns

14

In [8]:
df_1 = df_1.iloc[:,0:total_columns-2]
df_2 = df_2.iloc[:,0:total_columns-2]
df_3 = df_3.iloc[:,0:total_columns-2]
df_1

,Siebnr.:,do,du,Gewicht,Tara,Massenanteil [g],Massenanteil [%],Durchgang ∑ [%],g*M1,g*M2,g*M3,Massenanteil NT [g]
0,1,1.4,1,300.17,300.16,0.01,0.019685,99.9803,0.188333,0.0118322,0.09,300.17
1,2,1,0.71,272.75,272.73,0.02,0.0393701,99.9409,0.528655,0.0168523,0.3,272.75
2,3,0.71,0.5,258.03,258,0.03,0.0590551,99.8819,1.12066,0.0178746,0.75,258.03
3,4,0.5,0.355,234.68,234.39,0.29,0.570866,99.311,15.331,0.122179,10.15,234.68
4,5,0.355,0.25,229.76,224.5,5.26,10.3543,88.9567,392.979,1.567,236.7,229.76
5,6,0.25,0.18,246.93,222.92,24.01,47.2638,41.6929,2523.84,5.09329,1440.6,246.93
6,7,0.18,0.125,229.97,212.95,17.02,33.5039,8.18898,2522.31,2.553,1378.62,229.97
7,8,0.125,0.09,207.48,203.6,3.88,7.6378,0.551181,815.702,0.411536,457.84,207.48
8,9,0.09,0.063,206.32,206.08,0.24,0.472441,0.0787402,70.902,0.0180719,39.36,206.32
9,10,0.063,0.02,216.62,216.58,0.04,0.0787402,0,21.7831,0.00141986,11,216.62
10,11,0.02,0,321.62,321.62,0,0,NaN,NaN,NaN,NaN,0

In [9]:
df_2

,Siebnr.:,do,du,Gewicht,Tara,Massenanteil [g],Massenanteil [%],Durchgang ∑ [%],g*M1,g*M2,g*M3,Massenanteil NT [g]
14,1,1.4,1,300.16,300.15,0.01,0.0198886,99.9801,0.188333,0.0118322,0.09,300.16
15,2,1,0.71,272.75,272.74,0.01,0.0198886,99.9602,0.264327,0.00842615,0.15,272.75
16,3,0.71,0.5,258.01,257.98,0.03,0.0596659,99.9006,1.12066,0.0178746,0.75,258.01
17,4,0.5,0.355,234.67,234.37,0.3,0.596659,99.3039,15.8596,0.126392,10.5,234.67
18,5,0.355,0.25,229.74,224.51,5.23,10.4018,88.9021,390.737,1.55807,235.35,229.74
19,6,0.25,0.18,246.92,223.01,23.91,47.5537,41.3484,2513.33,5.07208,1434.6,246.92
20,7,0.18,0.125,229.68,212.95,16.73,33.2737,8.07478,2479.33,2.5095,1355.13,229.68
21,8,0.125,0.09,207.43,203.61,3.82,7.59745,0.477327,803.088,0.405172,450.76,207.43
22,9,0.09,0.063,206.33,206.12,0.21,0.417661,0.0596659,62.0392,0.0158129,34.44,206.33
23,10,0.063,0.02,216.63,216.6,0.03,0.0596659,0,16.3373,0.00106489,8.25,216.63
24,11,0.02,0,321.62,321.62,0,0,NaN,NaN,NaN,NaN,321.62

In [10]:
df_3

,Siebnr.:,do,du,Gewicht,Tara,Massenanteil [g],Massenanteil [%],Durchgang ∑ [%],g*M1,g*M2,g*M3,Massenanteil NT [g]
28,1,1.4,1,300.17,300.15,0.02,0.0397062,99.9603,0.376667,0.0236643,0.18,300.17
29,2,1,0.71,272.76,272.74,0.02,0.0397062,99.9206,0.528655,0.0168523,0.3,272.76
30,3,0.71,0.5,258.01,257.98,0.03,0.0595593,99.861,1.12066,0.0178746,0.75,258.01
31,4,0.5,0.355,234.67,234.37,0.3,0.595593,99.2654,15.8596,0.126392,10.5,234.67
32,5,0.355,0.25,229.64,224.51,5.13,10.1846,89.0808,383.266,1.52828,230.85,229.64
33,6,0.25,0.18,247.19,223.01,24.18,48.0048,41.076,2541.71,5.12935,1450.8,247.19
34,7,0.18,0.125,229.52,212.95,16.57,32.8966,8.17947,2455.62,2.4855,1342.17,229.52
35,8,0.125,0.09,207.52,203.61,3.91,7.76256,0.416915,822.009,0.414718,461.38,207.52
36,9,0.09,0.063,206.3,206.12,0.18,0.357356,0.0595593,53.1765,0.0135539,29.52,206.3
37,10,0.063,0.02,216.63,216.6,0.03,0.0595593,0,16.3373,0.00106489,8.25,216.63
38,11,0.02,0,321.62,321.62,0,0,NaN,NaN,NaN,NaN,321.62

In [12]:
# configurations
# For probe-1 => spez Oberfl. [cm²/g] = 125.29 , MK calc [mm] = 0.19 , AFS = 70 , MK [mm] = 0.27 , GG[%] = 81.19
# For probe-2 => spez Oberfl. [cm²/g] = 124.95 , MK calc [mm] = 0.19 , AFS = 70 , MK [mm] = 0.27 , GG[%] = 81.18
# For probe-3 => spez Oberfl. [cm²/g] = 124.88 , MK calc [mm] = 0.19 , AFS = 70 , MK [mm] = 0.27 , GG[%] = 81.25

In [13]:
def get_configs(a,b,c,d,e):
    spez = []
    Mk_calc = []
    AFS = []
    MK = []
    GG = []
    for x in range(len(df_1)):
        spez.append(a)
        Mk_calc.append(b)
        AFS.append(c)
        MK.append(d)
        GG.append(e)

    return spez,Mk_calc,AFS,MK,GG

In [14]:
spez,Mk_calc,AFS,MK,GG   = get_configs(125.29,0.19,70,0.27,81.19) # for probe-1
df_1['spez Oberfl. [cm²/g]'] = spez
df_1['MK calc [mm]'] = Mk_calc
df_1['AFS'] = AFS
df_1['MK [mm]'] = MK
df_1['GG [%]'] = GG

spez,Mk_calc,AFS,MK,GG   = get_configs(124.95,0.19,70,0.27,81.18) # for probe-2
df_2['spez Oberfl. [cm²/g]'] = spez
df_2['MK calc [mm]'] = Mk_calc
df_2['AFS'] = AFS
df_2['MK [mm]'] = MK
df_2['GG [%]'] = GG

spez,Mk_calc,AFS,MK,GG   = get_configs(124.88,0.19,70,0.27,81.25) # for probe-3
df_3['spez Oberfl. [cm²/g]'] = spez
df_3['MK calc [mm]'] = Mk_calc
df_3['AFS'] = AFS
df_3['MK [mm]'] = MK
df_3['GG [%]'] = GG

In [15]:
df_1.fillna(value=0,inplace=True)
df_2.fillna(value=0,inplace=True)
df_3.fillna(value=0,inplace=True)

In [16]:
# getting final dataframe
final_df = pd.concat([df_1,df_2,df_3],ignore_index=True)
final_df

,Siebnr.:,do,du,Gewicht,Tara,Massenanteil [g],Massenanteil [%],Durchgang ∑ [%],g*M1,g*M2,g*M3,Massenanteil NT [g],spez Oberfl. [cm²/g],MK calc [mm],AFS,MK [mm],GG [%]
0,1,1.400,1.000,300.17,300.16,0.01,0.019685,99.980315,0.188333,0.011832,0.09,300.17,125.29,0.19,70,0.27,81.19
1,2,1.000,0.710,272.75,272.73,0.02,0.039370,99.940945,0.528655,0.016852,0.30,272.75,125.29,0.19,70,0.27,81.19
2,3,0.710,0.500,258.03,258.00,0.03,0.059055,99.881890,1.120661,0.017875,0.75,258.03,125.29,0.19,70,0.27,81.19
3,4,0.500,0.355,234.68,234.39,0.29,0.570866,99.311024,15.330994,0.122179,10.15,234.68,125.29,0.19,70,0.27,81.19
4,5,0.355,0.250,229.76,224.50,5.26,10.354331,88.956693,392.978512,1.567003,236.70,229.76,125.29,0.19,70,0.27,81.19
5,6,0.250,0.180,246.93,222.92,24.01,47.263780,41.692913,2523.841860,5.093290,1440.60,246.93,125.29,0.19,70,0.27,81.19
6,7,0.180,0.125,229.97,212.95,17.02,33.503937,8.188976,2522.308197,2.553000,1378.62,229.97,125.29,0.19,70,0.27,81.19
7,8,0.125,0.090,207.48,203.60,3.88,7.637795,0.551181,815.702326,0.411536,457.84,207.48,125.29,0.19,70,0.27,81.19
8,9,0.090,0.063,206.32,206.08,0.24,0.472441,0.078740,70.901961,0.018072,39.36,206.32,125.29,0.19,70,0.27,81.19
9,10,0.063,0.020,216.62,216.58,0.04,0.078740,0.000000,21.783133,0.001420,11.00,216.62,125.29,0.19,70,0.27,81.19
10,11,0.020,0.000,321.62,321.62,0.00,0.000000,0.000000,0.000000,0.000000,0.00,0.00,125.29,0.19,70,0.27,81.19
11,1,1.400,1.000,300.16,300.15,0.01,0.019889,99.980111,0.188333,0.011832,0.09,300.16,124.95,0.19,70,0.27,81.18
12,2,1.000,0.710,272.75,272.74,0.01,0.019889,99.960223,0.264327,0.008426,0.15,272.75,124.95,0.19,70,0.27,81.18
13,3,0.710,0.500,258.01,257.98,0.03,0.059666,99.900557,1.120661,0.017875,0.75,258.01,124.95,0.19,70,0.27,81.18
14,4,0.500,0.355,234.67,234.37,0.30,0.596659,99.303898,15.859649,0.126392,10.50,234.67,124.95,0.19,70,0.27,81.18
15,5,0.355,0.250,229.74,224.51,5.23,10.401750,88.902148,390.737190,1.558066,235.35,229.74,124.95,0.19,70,0.27,81.18
16,6,0.250,0.180,246.92,223.01,23.91,47.553699,41.348449,2513.330233,5.072077,1434.60,246.92,124.95,0.19,70,0.27,81.18
17,7,0.180,0.125,229.68,212.95,16.73,33.273667,8.074781,2479.331148,2.509500,1355.13,229.68,124.95,0.19,70,0.27,81.18
18,8,0.125,0.090,207.43,203.61,3.82,7.597454,0.477327,803.088372,0.405172,450.76,207.43,124.95,0.19,70,0.27,81.18
19,9,0.090,0.063,206.33,206.12,0.21,0.417661,0.059666,62.039216,0.015813,34.44,206.33,124.95,0.19,70,0.27,81.18
20,10,0.063,0.020,216.63,216.60,0.03,0.059666,0.000000,16.337349,0.001065,8.25,216.63,124.95,0.19,70,0.27,81.18
21,11,0.020,0.000,321.62,321.62,0.00,0.000000,0.000000,0.000000,0.000000,0.00,321.62,124.95,0.19,70,0.27,81.18
22,1,1.400,1.000,300.17,300.15,0.02,0.039706,99.960294,0.376667,0.023664,0.18,300.17,124.88,0.19,70,0.27,81.25
23,2,1.000,0.710,272.76,272.74,0.02,0.039706,99.920588,0.528655,0.016852,0.30,272.76,124.88,0.19,70,0.27,81.25
24,3,0.710,0.500,258.01,257.98,0.03,0.059559,99.861028,1.120661,0.017875,0.75,258.01,124.88,0.19,70,0.27,81.25
25,4,0.500,0.355,234.67,234.37,0.30,0.595593,99.265436,15.859649,0.126392,10.50,234.67,124.88,0.19,70,0.27,81.25
26,5,0.355,0.250,229.64,224.51,5.13,10.184634,89.080802,383.266116,1.528275,230.85,229.64,124.88,0.19,70,0.27,81.25
27,6,0.250,0.180,247.19,223.01,24.18,48.004765,41.076037,2541.711628,5.129353,1450.80,247.19,124.88,0.19,70,0.27,81.25
28,7,0.180,0.125,229.52,212.95,16.57,32.896565,8.179472,2455.619672,2.485500,1342.17,229.52,124.88,0.19,70,0.27,81.25
29,8,0.125,0.090,207.52,203.61,3.91,7.762557,0.416915,822.009302,0.414718,461.38,207.52,124.88,0.19,70,0.27,81.25
30,9,0.090,0.063,206.30,206.12,0.18,0.357356,0.059559,53.176471,0.013554,29.52,206.30,124.88,0.19,70,0.27,81.25
31,10,0.063,0.020,216.63,216.60,0.03,0.059559,0.000000,16.337349,0.001065,8.25,216.63,124.88,0.19,70,0.27,81.25
32,11,0.020,0.000,321.62,321.62,0.00,0.000000,0.000000,0.000000,0.000000,0.00,321.62,124.88,0.19,70,0.27,81.25

In [17]:
# check correlation
correlation_data = final_df.corr()
cols_to_be_selected = []
all_cols = correlation_data.columns
index = 0;

for x in correlation_data['Massenanteil [%]'].tolist():
    if(x >= -0.25 and x <=0.25):
        #neglecting the feature / column
        pass
    else:
        cols_to_be_selected.append(all_cols[index])
    index += 1

cols_to_be_selected

['do',
 'du',
 'Tara',
 'Massenanteil [g]',
 'Massenanteil [%]',
 'g*M1',
 'g*M2',
 'g*M3',
 'AFS']

In [18]:
features = final_df[['do',
 'du',
 'Tara',
 'Massenanteil [g]',
 'g*M1',
 'g*M2',
 'g*M3',
 'AFS']]

target = final_df[['Massenanteil [%]']]

In [19]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_validate
reg = LinearRegression()
model = cross_validate(reg,features,target,cv=10,scoring='r2',return_estimator=True)
model

{'estimator': [LinearRegression(),
  LinearRegression(),
  LinearRegression(),
  LinearRegression(),
  LinearRegression(),
  LinearRegression(),
  LinearRegression(),
  LinearRegression(),
  LinearRegression(),
  LinearRegression()],
 'fit_time': array([0.01396203, 0.00801039, 0.004987  , 0.00800967, 0.00498843,
        0.00498748, 0.00797868, 0.00797772, 0.00598383, 0.00498748]),
 'score_time': array([0.00398993, 0.00395966, 0.00598264, 0.00495529, 0.00299168,
        0.00501561, 0.00595307, 0.00399303, 0.00299168, 0.00299072]),
 'test_score': array([0.99988919, 0.99971058, 0.99980371, 0.99998087, 0.99981995,
        0.9999426 , 0.99982754, 0.99998173, 0.99995235, 0.99999593])}

In [35]:
final_model = model['estimator'][0]
final_model.coef_

array([[-5.55997913e-02,  7.67491386e-02, -1.02085719e-05,
         1.98485492e+00, -4.74378584e-05, -1.11212200e-02,
         5.49577135e-05,  0.00000000e+00]])

In [21]:
final_model.intercept_

array([0.00443097])

In [34]:
# So the final equation is :
# [ (do * -0.0555) +  (du * 0.0767) + (Tara * - 0.0000102 ) + (Massenanteil [g] * 1.984) + (g*M1 * -0.000474 ) + (g*M2 * -0.0111 ) + (g*M3 * 0.0000549 )  ] + 0.00443097
'''[ (do * -0.0555) +  (du * 0.0767) + (Tara * - 0.0000102 ) + (Massenanteil [g] * 1.984) + (g*M1 * -0.000474 ) + (g*M2 * -0.0111 ) + (g*M3 * 0.0000549 )  ] + 0.00443097'''

'[ (do * -0.0555) +  (du * 0.0767) + (Tara * - 0.0000102 ) + (Massenanteil [g] * 1.984) + (g*M1 * -0.000474 ) + (g*M2 * -0.0111 ) + (g*M3 * 0.0000549 )  ] + 0.00443097'

In [35]:
# This equation will help us to predict Massenanteil [%]