# Importing Libraries

In [1]:
import pandas as pd
import numpy as np

# Reading Data File

In [2]:
df  = pd.read_csv('data/MissingData.csv',na_filter=np.nan)
df

,order_id,customer_id,date,nearest_warehouse,shopping_cart,order_price,delivery_charges,customer_lat,customer_long,coupon_discount,order_total,season,is_expedited_delivery,distance_to_nearest_warehouse,latest_customer_review,is_happy_customer
0,ORD302061,ID3163980132,2019-12-09,Thompson,"[('iAssist Line', 2), ('Toshika 750', 2)]",13090.0,78.07,-37.803418,144.956843,5,12513.57,Summer,False,1.3418,for the price it's not bad. screen isn't much ...,1.0
1,ORD280336,ID0060088409,2019-03-19,Nickolson,"[('Thunder line', 1), ('Olivia x460', 2)]",4630.0,NaN,-37.819467,144.984089,5,4478.54,Autumn,True,1.2821,great phone great phone,1.0
2,ORD011529,ID0634783346,2019-05-26,Thompson,"[('Olivia x460', 1), ('Universe Note', 1)]",4675.0,NaN,-37.812163,144.938758,0,4739.95,Autumn,False,0.7331,great for a heavily used phone for the few mon...,1.0
3,ORD488462,ID2189161536,2019-06-25,Nickolson,"[('Toshika 750', 2), ('iStream', 2), ('Thunder...",11120.0,66.44,-37.817613,144.959110,25,8406.44,Winter,False,0.9247,five stars i love the phone thinking about buy...,1.0
4,ORD233831,ID2174950793,2019-09-07,Thompson,"[('Thunder line', 2), ('pearTV', 2), ('Alcon 1...",25930.0,78.40,-37.819023,144.954049,10,23415.40,Spring,False,0.9361,very good quality for the price never been an ...,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,ORD316275,ID0477079441,2019-06-11,Nickolson,"[('pearTV', 1), ('Toshika 750', 2), ('Lucent 3...",16180.0,52.87,-37.807455,144.974837,15,13805.87,Winter,False,1.3243,give a lot of problem!!!! i buy this for my mo...,0.0
496,ORD420898,ID0702363985,2019-09-04,NaN,"[('Thunder line', 2), ('iAssist Line', 1), ('U...",10035.0,77.00,-37.805525,144.941074,5,9610.25,Spring,False,0.9546,dual sim works fine phone works with t-mobile ...,1.0
497,ORD031180,ID0356099263,2019-09-04,Bakers,"[('pearTV', 2), ('iStream', 2), ('Olivia x460'...",15370.0,78.97,-37.819978,144.992569,25,11606.47,Spring,False,1.1355,no headphones but other then that i love my ph...,1.0
498,ORD096213,ID4315294440,2019-04-04,Thompson,"[('Candle Inferno', 1), ('Thunder line', 1), (...",11250.0,63.96,-37.817171,144.953314,0,11313.96,Autumn,True,0.7432,bad condition i received it with open carton &...,0.0
499,ORD129051,ID0441588019,2019-08-31,Thompson,"[('iStream', 1), ('Universe Note', 2), ('pearT...",23990.0,77.69,-37.811739,144.936152,10,21668.69,Winter,True,0.9656,huawei=quality quality piece. love it.,1.0

# Handling Missing Values

In [3]:
# Getting Length of Dataframe
num_rows = len(df)
num_rows

500

In [4]:
#Checking which columns contain null or missing values
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 16 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       500 non-null    object
 1   customer_id                    500 non-null    object
 2   date                           500 non-null    object
 3   nearest_warehouse              445 non-null    object
 4   shopping_cart                  500 non-null    object
 5   order_price                    485 non-null    float64
 6   delivery_charges               460 non-null    float64
 7   customer_lat                   500 non-null    float64
 8   customer_long                  500 non-null    float64
 9   coupon_discount                500 non-null    int64
 10  order_total                    485 non-null    float64
 11  season                         500 non-null    object
 12  is_expedited_delivery          500 non-null    bool
 13  distance_to_nearest_warehouse  469 non-null    float64
 14  latest_customer_review         500 non-null    object
 15  is_happy_customer              460 non-null    float64
dtypes: bool(1), float64(7), int64(1), object(7)
memory usage: 59.2+ KB

###  By looking at the output above, we can clearly see that following columns contains missing values:
###  1. nearest_warehouse
###  2. order_price
###  3. delivery_charges
###  4. order_total
###  5. disance_to_nearest_warehouse
###  6. is_happy_customer

##  Coming towards nearest warehoue & distance to nearest_warehouse
### Use the formula D2 = X2 + Y2 to find the squared distance between two points. For example, if X = 4 and Y = 5, then D2 = 42 + 52 = 41. Thus, the square of the distance between the coordinates is 41.

In [5]:
def get_nearest_warehouse(lat,long):

    baker_lat = -37.8099961
    baker_long = 144.995232

    thompson_lat = -37.8126732
    thompson_long = 144.9470689

    nikolson_lat = -37.818595
    nikolson_long = 144.995232
    
    results = [np.abs(lat-baker_lat)**2 + np.abs(long-baker_long)**2,np.abs(lat-thompson_lat)**2 + np.abs(long-thompson_long)**2,np.abs(lat-nikolson_lat)**2 + np.abs(long-nikolson_long)**2 ]
    value = min(results)
    index  = results.index(value)
    
    if(index==0):
        return "Bakers"
    if(index==1):
        return "Thompson"
    if(index==2):
        return "Nickolson"
    

def get_distance_from_nearest_warehouse(lat,long,warehouse):
    if(warehouse=='Thompson'):
        return (np.abs(-37.8126732-lat)**2 + np.abs(144.9470689-long)**2 )**(1/2)
    elif(warehouse=='Bakers'):
        return (np.abs(-37.8099961-lat)**2 + np.abs(144.995232-long)**2 )**(1/2)
    elif(warehouse=='Nickolson'):
        return (np.abs(37.818595-lat)**2 + np.abs(144.969551-long)**2 )**(1/2)

for i in range(0,len(df)):
    warehouse = df.iloc[i]['nearest_warehouse']
    if(type(warehouse)==float):
        lat = df.iloc[i]['customer_lat']
        long = df.iloc[i]['customer_long']
        df.at[i,'nearest_warehouse'] = get_nearest_warehouse(lat,long) 

for i in range(0,len(df)):
    warehouse = df.iloc[i]['nearest_warehouse']
    if(np.isnan(df.iloc[i]['distance_to_nearest_warehouse'])==True):
        lat = df.iloc[i]['customer_lat']
        long = df.iloc[i]['customer_long']
        df.at[i,'distance_to_nearest_warehouse'] = np.round(get_distance_from_nearest_warehouse(lat,long,warehouse),4)

### Checking the dataframe for nan/missing values

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 16 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       500 non-null    object
 1   customer_id                    500 non-null    object
 2   date                           500 non-null    object
 3   nearest_warehouse              500 non-null    object
 4   shopping_cart                  500 non-null    object
 5   order_price                    485 non-null    float64
 6   delivery_charges               460 non-null    float64
 7   customer_lat                   500 non-null    float64
 8   customer_long                  500 non-null    float64
 9   coupon_discount                500 non-null    int64
 10  order_total                    485 non-null    float64
 11  season                         500 non-null    object
 12  is_expedited_delivery          500 non-null    bool
 13  distance_to_nearest_warehouse  500 non-null    float64
 14  latest_customer_review         500 non-null    object
 15  is_happy_customer              460 non-null    float64
dtypes: bool(1), float64(7), int64(1), object(7)
memory usage: 59.2+ KB

### For delivery chargers, we will use linear regression model to find best equation based on season, warehouse distance, expected delivery ,happy with previous purchase

In [7]:
df_missing_dc = df[['delivery_charges','distance_to_nearest_warehouse','season','is_expedited_delivery','is_happy_customer']]

### Checking the dataframe for nan/missing values

In [8]:
df_missing_dc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 5 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   delivery_charges               460 non-null    float64
 1   distance_to_nearest_warehouse  500 non-null    float64
 2   season                         500 non-null    object
 3   is_expedited_delivery          500 non-null    bool
 4   is_happy_customer              460 non-null    float64
dtypes: bool(1), float64(3), object(1)
memory usage: 16.2+ KB

### Converting all happy_customers missing value to happy(1) as for prediction of delivery charges for now.

In [9]:
#Assuming all customers that dont have any previous deliveries, are happy for now.
df_missing_dc['is_happy_customer'] = df_missing_dc['is_happy_customer'].fillna(value=1.0)

#Mapping dictionary to is_expected_Delivery
map_dict = {np.bool_(False):0,np.bool_(True):1}
df_missing_dc['is_expedited_delivery'] = df_missing_dc['is_expedited_delivery'].map(map_dict)

C:\Users\S.M.Ammar\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\S.M.Ammar\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

### Getting all delivery charges which contains no null / missing values for model training

In [10]:

df_missing_dc =  df_missing_dc[df_missing_dc['delivery_charges'].notna()]
df_missing_dc

,delivery_charges,distance_to_nearest_warehouse,season,is_expedited_delivery,is_happy_customer
0,78.07,1.3418,Summer,0,1.0
3,66.44,0.9247,Winter,0,1.0
4,78.40,0.9361,Spring,0,1.0
5,64.97,0.5849,Autumn,0,1.0
6,66.19,1.0306,Autumn,0,1.0
...,...,...,...,...,...
495,52.87,1.3243,Winter,0,0.0
496,77.00,0.9546,Spring,0,1.0
497,78.97,1.1355,Spring,0,1.0
498,63.96,0.7432,Autumn,1,0.0
499,77.69,0.9656,Winter,1,1.0

### Converting season feature into three different features using Hot-One Encoding
### To avoid the dummy variable trap, we will skip one of the four features in season

In [11]:
seasons = pd.get_dummies(df_missing_dc['season'],drop_first=True)
df_missing_dc = pd.concat([df_missing_dc,seasons],axis=1)
df_missing_dc.drop(columns=['season'],inplace=True)
df_missing_dc

,delivery_charges,distance_to_nearest_warehouse,is_expedited_delivery,is_happy_customer,Spring,Summer,Winter
0,78.07,1.3418,0,1.0,0,1,0
3,66.44,0.9247,0,1.0,0,0,1
4,78.40,0.9361,0,1.0,1,0,0
5,64.97,0.5849,0,1.0,0,0,0
6,66.19,1.0306,0,1.0,0,0,0
...,...,...,...,...,...,...,...
495,52.87,1.3243,0,0.0,0,0,1
496,77.00,0.9546,0,1.0,1,0,0
497,78.97,1.1355,0,1.0,1,0,0
498,63.96,0.7432,1,0.0,0,0,0
499,77.69,0.9656,1,1.0,0,0,1

### Building "Linear Regression Model" to predict delivery charges

In [12]:
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

target = np.array(df_missing_dc['delivery_charges'])
features = np.array(df_missing_dc[['distance_to_nearest_warehouse','is_expedited_delivery','is_happy_customer','Spring','Summer','Winter']])

train_features, test_features, train_labels, test_labels = train_test_split(features, target, test_size = 0.25, random_state = 42)

delivery_charge_model = LinearRegression().fit(train_features, train_labels)

### Checking mathematical equation

In [13]:
delivery_charge_model.coef_,delivery_charge_model.intercept_

(array([ 0.11421462, 17.63179043, 14.61936933, 16.58812878, 11.78587603,
        -2.1562378 ]), 49.5657935330476)

### Checking model accuracy

In [14]:
from sklearn.metrics import r2_score
preds = delivery_charge_model.predict(test_features)
r2_score(test_labels, preds)

0.9070865959364016

### Using "Trained Delivery Charge Model" to predict missing values

In [15]:
#using delivery model to fill missing values of delivery charges
df_cover_delivery = df[['delivery_charges','distance_to_nearest_warehouse','season','is_expedited_delivery','is_happy_customer']]
#Assuming all customers that dont have any previous deliveries, are happy for now.
df_cover_delivery['is_happy_customer'] = df_cover_delivery['is_happy_customer'].fillna(value=1.0)

#Mapping dictionary to is_expected_Delivery
map_dict = {np.bool_(False):0,np.bool_(True):1}
df_cover_delivery['is_expedited_delivery'] = df_cover_delivery['is_expedited_delivery'].map(map_dict)
seasons = pd.get_dummies(df_cover_delivery['season'],drop_first=True)
df_cover_delivery = pd.concat([df_cover_delivery,seasons],axis=1)
df_cover_delivery.drop(columns=['season'],inplace=True)
df_cover_delivery

C:\Users\S.M.Ammar\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
C:\Users\S.M.Ammar\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,delivery_charges,distance_to_nearest_warehouse,is_expedited_delivery,is_happy_customer,Spring,Summer,Winter
0,78.07,1.3418,0,1.0,0,1,0
1,NaN,1.2821,1,1.0,0,0,0
2,NaN,0.7331,0,1.0,0,0,0
3,66.44,0.9247,0,1.0,0,0,1
4,78.40,0.9361,0,1.0,1,0,0
...,...,...,...,...,...,...,...
495,52.87,1.3243,0,0.0,0,0,1
496,77.00,0.9546,0,1.0,1,0,0
497,78.97,1.1355,0,1.0,1,0,0
498,63.96,0.7432,1,0.0,0,0,0
499,77.69,0.9656,1,1.0,0,0,1

In [16]:
df_cover_delivery.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 7 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   delivery_charges               460 non-null    float64
 1   distance_to_nearest_warehouse  500 non-null    float64
 2   is_expedited_delivery          500 non-null    int64
 3   is_happy_customer              500 non-null    float64
 4   Spring                         500 non-null    uint8
 5   Summer                         500 non-null    uint8
 6   Winter                         500 non-null    uint8
dtypes: float64(3), int64(1), uint8(3)
memory usage: 17.2 KB

In [17]:
#filling missing values with help of model
for x in range(0,len(df_cover_delivery)):
    if(np.isnan(df_cover_delivery.iloc[x]['delivery_charges'])):
        features = np.array(df_cover_delivery.iloc[x][['distance_to_nearest_warehouse','is_expedited_delivery','is_happy_customer','Spring','Summer','Winter']])
        df_cover_delivery.at[x,'delivery_charges'] = delivery_charge_model.predict(features.reshape(1,-1))[0]

#updating delivery_charges column to orginal dataframe
df['delivery_charges'] = df_cover_delivery['delivery_charges']
df

,order_id,customer_id,date,nearest_warehouse,shopping_cart,order_price,delivery_charges,customer_lat,customer_long,coupon_discount,order_total,season,is_expedited_delivery,distance_to_nearest_warehouse,latest_customer_review,is_happy_customer
0,ORD302061,ID3163980132,2019-12-09,Thompson,"[('iAssist Line', 2), ('Toshika 750', 2)]",13090.0,78.070000,-37.803418,144.956843,5,12513.57,Summer,False,1.3418,for the price it's not bad. screen isn't much ...,1.0
1,ORD280336,ID0060088409,2019-03-19,Nickolson,"[('Thunder line', 1), ('Olivia x460', 2)]",4630.0,81.963388,-37.819467,144.984089,5,4478.54,Autumn,True,1.2821,great phone great phone,1.0
2,ORD011529,ID0634783346,2019-05-26,Thompson,"[('Olivia x460', 1), ('Universe Note', 1)]",4675.0,64.268894,-37.812163,144.938758,0,4739.95,Autumn,False,0.7331,great for a heavily used phone for the few mon...,1.0
3,ORD488462,ID2189161536,2019-06-25,Nickolson,"[('Toshika 750', 2), ('iStream', 2), ('Thunder...",11120.0,66.440000,-37.817613,144.959110,25,8406.44,Winter,False,0.9247,five stars i love the phone thinking about buy...,1.0
4,ORD233831,ID2174950793,2019-09-07,Thompson,"[('Thunder line', 2), ('pearTV', 2), ('Alcon 1...",25930.0,78.400000,-37.819023,144.954049,10,23415.40,Spring,False,0.9361,very good quality for the price never been an ...,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,ORD316275,ID0477079441,2019-06-11,Nickolson,"[('pearTV', 1), ('Toshika 750', 2), ('Lucent 3...",16180.0,52.870000,-37.807455,144.974837,15,13805.87,Winter,False,1.3243,give a lot of problem!!!! i buy this for my mo...,0.0
496,ORD420898,ID0702363985,2019-09-04,Thompson,"[('Thunder line', 2), ('iAssist Line', 1), ('U...",10035.0,77.000000,-37.805525,144.941074,5,9610.25,Spring,False,0.9546,dual sim works fine phone works with t-mobile ...,1.0
497,ORD031180,ID0356099263,2019-09-04,Bakers,"[('pearTV', 2), ('iStream', 2), ('Olivia x460'...",15370.0,78.970000,-37.819978,144.992569,25,11606.47,Spring,False,1.1355,no headphones but other then that i love my ph...,1.0
498,ORD096213,ID4315294440,2019-04-04,Thompson,"[('Candle Inferno', 1), ('Thunder line', 1), (...",11250.0,63.960000,-37.817171,144.953314,0,11313.96,Autumn,True,0.7432,bad condition i received it with open carton &...,0.0
499,ORD129051,ID0441588019,2019-08-31,Thompson,"[('iStream', 1), ('Universe Note', 2), ('pearT...",23990.0,77.690000,-37.811739,144.936152,10,21668.69,Winter,True,0.9656,huawei=quality quality piece. love it.,1.0

### Checking the dataframe for nan/missing values

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 16 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       500 non-null    object
 1   customer_id                    500 non-null    object
 2   date                           500 non-null    object
 3   nearest_warehouse              500 non-null    object
 4   shopping_cart                  500 non-null    object
 5   order_price                    485 non-null    float64
 6   delivery_charges               500 non-null    float64
 7   customer_lat                   500 non-null    float64
 8   customer_long                  500 non-null    float64
 9   coupon_discount                500 non-null    int64
 10  order_total                    485 non-null    float64
 11  season                         500 non-null    object
 12  is_expedited_delivery          500 non-null    bool
 13  distance_to_nearest_warehouse  500 non-null    float64
 14  latest_customer_review         500 non-null    object
 15  is_happy_customer              460 non-null    float64
dtypes: bool(1), float64(7), int64(1), object(7)
memory usage: 59.2+ KB

### Now we have 3 features that contain missing values

### 1. is_happy_customer
### 2. order_price
### 3. order_total

### For is_happy_customer, we will use Sentiment Intensity Analyzer and calculate polarity score. Based on polarity score, we will fill the missing values

In [19]:
import nltk
from nltk.sentiment.vader import SentimentIntensityAnalyzer
sid = SentimentIntensityAnalyzer()

for x in range(0,len(df)):
    if(np.isnan(df.iloc[x]['is_happy_customer'])):
        ss = sid.polarity_scores(df.iloc[x]['latest_customer_review'])
        if(ss['compound'] >= 0.05):
             df.at[x,'is_happy_customer'] = 1.0
        else:
            df.at[x,'is_happy_customer'] = 0.0

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 16 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       500 non-null    object
 1   customer_id                    500 non-null    object
 2   date                           500 non-null    object
 3   nearest_warehouse              500 non-null    object
 4   shopping_cart                  500 non-null    object
 5   order_price                    485 non-null    float64
 6   delivery_charges               500 non-null    float64
 7   customer_lat                   500 non-null    float64
 8   customer_long                  500 non-null    float64
 9   coupon_discount                500 non-null    int64
 10  order_total                    485 non-null    float64
 11  season                         500 non-null    object
 12  is_expedited_delivery          500 non-null    bool
 13  distance_to_nearest_warehouse  500 non-null    float64
 14  latest_customer_review         500 non-null    object
 15  is_happy_customer              500 non-null    float64
dtypes: bool(1), float64(7), int64(1), object(7)
memory usage: 59.2+ KB

### Processing & Analyzing Shopping Cart

### We will be using linear regression approach for predicting order price. To accquire order price, we must know the price of each 10 items.

### In order to accquire items price, we will form multiple linear eqautions based on shopping cart.

In [21]:
#storing every item in a dictionary
# giving varaibles to every item for linear equation
org_df = df
items_dict = {}
chars = ['a','b','c','d','e','f','g','h','i','j']
order_price = []
df =  df[df['order_price'].notna()]
index = 0

for x in range(0,len(df)):
        order_price.append(df.iloc[x]['order_price'])
        item = (df.iloc[x]['shopping_cart']).replace(']','')
        item = item.replace('[','')
        item = item.replace('(','')
        item = item.replace(')','')
        item = item.replace("'",'')
        item = item.split(',')
        for y in range(0,len(item),2):
            if(item[y].replace(' ','') not in items_dict.keys()):
                items_dict[item[y].replace(' ','')] = chars[index]
                index = index + 1

In [22]:
items_dict

{'Alcon10': 'h',
 'CandleInferno': 'j',
 'Lucent330S': 'i',
 'Oliviax460': 'd',
 'Thunderline': 'c',
 'Toshika750': 'b',
 'UniverseNote': 'e',
 'iAssistLine': 'a',
 'iStream': 'f',
 'pearTV': 'g'}

In [23]:
#Making multiple linear equations
eqautions = []

for x in range(0,len(df)):
        item = (df.iloc[x]['shopping_cart']).replace(']','')
        item = item.replace('[','')
        item = item.replace('(','')
        item = item.replace(')','')
        item = item.replace("'",'')
        item = item.split(',')
        equation = [0,0,0,0,0,0,0,0,0,0]
        for y in range(0,len(item),2):
            it = item[y].replace(' ','')
            variable = items_dict[it]
            if(variable=='a'):
                equation[0] = int(item[y+1].replace(' ',''))
            elif(variable=='b'):
                equation[1] = int(item[y+1].replace(' ',''))
            elif(variable=='c'):
                equation[2] = int(item[y+1].replace(' ',''))
            elif(variable=='d'):
                equation[3] = int(item[y+1].replace(' ',''))
            elif(variable=='e'):
                equation[4] = int(item[y+1].replace(' ',''))
            elif(variable=='f'):
                equation[5] = int(item[y+1].replace(' ',''))
            elif(variable=='g'):
                equation[6] = int(item[y+1].replace(' ',''))
            elif(variable=='h'):
                equation[7] = int(item[y+1].replace(' ',''))
            elif(variable=='i'):
                equation[8] = int(item[y+1].replace(' ',''))
            elif(variable=='j'):
                equation[9] = int(item[y+1].replace(' ',''))
        eqautions.append(equation)

### Now using all linear equations as input features for Linear Regression

In [24]:
#training model for order price
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

target = np.array(df['order_price'])
features = np.array(eqautions)

train_features, test_features, train_labels, test_labels = train_test_split(features, target, test_size = 0.25, random_state = 42)

order_model = LinearRegression().fit(train_features, train_labels)

### Checking mathematical equation

In [25]:
#prices of items
order_model.coef_,order_model.intercept_

(array([2225., 4320., 2180., 1225., 3450.,  150., 6310., 8950., 1230.,
         430.]), 7.275957614183426e-12)

### Checking model accuracy

In [26]:
from sklearn.metrics import r2_score
preds = order_model.predict(test_features)
r2_score(test_labels, preds)

1.0

### Building Linear equations for missing order price

In [27]:
#Making multiple linear equations
eqautions = []
df =  org_df[org_df['order_price'].isna()]
for x in range(0,len(df)):
        item = (df.iloc[x]['shopping_cart']).replace(']','')
        item = item.replace('[','')
        item = item.replace('(','')
        item = item.replace(')','')
        item = item.replace("'",'')
        item = item.split(',')
        equation = [0,0,0,0,0,0,0,0,0,0]
        for y in range(0,len(item),2):
            it = item[y].replace(' ','')
            variable = items_dict[it]
            if(variable=='a'):
                equation[0] = int(item[y+1].replace(' ',''))
            elif(variable=='b'):
                equation[1] = int(item[y+1].replace(' ',''))
            elif(variable=='c'):
                equation[2] = int(item[y+1].replace(' ',''))
            elif(variable=='d'):
                equation[3] = int(item[y+1].replace(' ',''))
            elif(variable=='e'):
                equation[4] = int(item[y+1].replace(' ',''))
            elif(variable=='f'):
                equation[5] = int(item[y+1].replace(' ',''))
            elif(variable=='g'):
                equation[6] = int(item[y+1].replace(' ',''))
            elif(variable=='h'):
                equation[7] = int(item[y+1].replace(' ',''))
            elif(variable=='i'):
                equation[8] = int(item[y+1].replace(' ',''))
            elif(variable=='j'):
                equation[9] = int(item[y+1].replace(' ',''))
        eqautions.append(equation)

### Predicting order_price for missing values

In [28]:
features = np.array(eqautions)
preds_order_ = order_model.predict(features)

In [29]:
# Filling missing values:
index = 0
for x in range(0,len(org_df)):
    if(np.isnan(org_df.iloc[x]['order_price'])):
        org_df.at[x,'order_price'] = round(preds_order_[index],2)
        index +=1

### Checking missing / null values

In [30]:
org_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 16 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       500 non-null    object
 1   customer_id                    500 non-null    object
 2   date                           500 non-null    object
 3   nearest_warehouse              500 non-null    object
 4   shopping_cart                  500 non-null    object
 5   order_price                    500 non-null    float64
 6   delivery_charges               500 non-null    float64
 7   customer_lat                   500 non-null    float64
 8   customer_long                  500 non-null    float64
 9   coupon_discount                500 non-null    int64
 10  order_total                    485 non-null    float64
 11  season                         500 non-null    object
 12  is_expedited_delivery          500 non-null    bool
 13  distance_to_nearest_warehouse  500 non-null    float64
 14  latest_customer_review         500 non-null    object
 15  is_happy_customer              500 non-null    float64
dtypes: bool(1), float64(7), int64(1), object(7)
memory usage: 59.2+ KB

### Filling missing values for order_total 

### The equation will be: (order_price - coupon%)+delivery_charges = order_total

In [31]:
for x in range(0,len(org_df)):
    if(np.isnan(org_df.iloc[x]['order_total'])):
        order_pr = org_df.iloc[x]['order_price']
        coupon = ((org_df.iloc[x]['coupon_discount'])/100 ) * order_pr
        delivery_rt = org_df.iloc[x]['delivery_charges']
        org_df.at[x,'order_total'] = round((order_pr-coupon)+delivery_rt,2)

In [32]:
org_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 16 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       500 non-null    object
 1   customer_id                    500 non-null    object
 2   date                           500 non-null    object
 3   nearest_warehouse              500 non-null    object
 4   shopping_cart                  500 non-null    object
 5   order_price                    500 non-null    float64
 6   delivery_charges               500 non-null    float64
 7   customer_lat                   500 non-null    float64
 8   customer_long                  500 non-null    float64
 9   coupon_discount                500 non-null    int64
 10  order_total                    500 non-null    float64
 11  season                         500 non-null    object
 12  is_expedited_delivery          500 non-null    bool
 13  distance_to_nearest_warehouse  500 non-null    float64
 14  latest_customer_review         500 non-null    object
 15  is_happy_customer              500 non-null    float64
dtypes: bool(1), float64(7), int64(1), object(7)
memory usage: 59.2+ KB

In [33]:
org_df

,order_id,customer_id,date,nearest_warehouse,shopping_cart,order_price,delivery_charges,customer_lat,customer_long,coupon_discount,order_total,season,is_expedited_delivery,distance_to_nearest_warehouse,latest_customer_review,is_happy_customer
0,ORD302061,ID3163980132,2019-12-09,Thompson,"[('iAssist Line', 2), ('Toshika 750', 2)]",13090.0,78.070000,-37.803418,144.956843,5,12513.57,Summer,False,1.3418,for the price it's not bad. screen isn't much ...,1.0
1,ORD280336,ID0060088409,2019-03-19,Nickolson,"[('Thunder line', 1), ('Olivia x460', 2)]",4630.0,81.963388,-37.819467,144.984089,5,4478.54,Autumn,True,1.2821,great phone great phone,1.0
2,ORD011529,ID0634783346,2019-05-26,Thompson,"[('Olivia x460', 1), ('Universe Note', 1)]",4675.0,64.268894,-37.812163,144.938758,0,4739.95,Autumn,False,0.7331,great for a heavily used phone for the few mon...,1.0
3,ORD488462,ID2189161536,2019-06-25,Nickolson,"[('Toshika 750', 2), ('iStream', 2), ('Thunder...",11120.0,66.440000,-37.817613,144.959110,25,8406.44,Winter,False,0.9247,five stars i love the phone thinking about buy...,1.0
4,ORD233831,ID2174950793,2019-09-07,Thompson,"[('Thunder line', 2), ('pearTV', 2), ('Alcon 1...",25930.0,78.400000,-37.819023,144.954049,10,23415.40,Spring,False,0.9361,very good quality for the price never been an ...,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,ORD316275,ID0477079441,2019-06-11,Nickolson,"[('pearTV', 1), ('Toshika 750', 2), ('Lucent 3...",16180.0,52.870000,-37.807455,144.974837,15,13805.87,Winter,False,1.3243,give a lot of problem!!!! i buy this for my mo...,0.0
496,ORD420898,ID0702363985,2019-09-04,Thompson,"[('Thunder line', 2), ('iAssist Line', 1), ('U...",10035.0,77.000000,-37.805525,144.941074,5,9610.25,Spring,False,0.9546,dual sim works fine phone works with t-mobile ...,1.0
497,ORD031180,ID0356099263,2019-09-04,Bakers,"[('pearTV', 2), ('iStream', 2), ('Olivia x460'...",15370.0,78.970000,-37.819978,144.992569,25,11606.47,Spring,False,1.1355,no headphones but other then that i love my ph...,1.0
498,ORD096213,ID4315294440,2019-04-04,Thompson,"[('Candle Inferno', 1), ('Thunder line', 1), (...",11250.0,63.960000,-37.817171,144.953314,0,11313.96,Autumn,True,0.7432,bad condition i received it with open carton &...,0.0
499,ORD129051,ID0441588019,2019-08-31,Thompson,"[('iStream', 1), ('Universe Note', 2), ('pearT...",23990.0,77.690000,-37.811739,144.936152,10,21668.69,Winter,True,0.9656,huawei=quality quality piece. love it.,1.0

In [34]:
org_df.to_csv('MissingValues-output.csv')